### ISSUE TITLE
Nested JSON file

### ISSUE THREAD

**Issue by Mikiyas721** [Flutterando/localization#8]
How do you access translations in nested JSON files.
{
  "a": {
    "b":{
      "c": "Translated with Flutter Localization"
    }
  }
}
print("a.b.c".i18n());
I was expecting something like this to work, but it does not. What am I missing?

**Comment by digibum** [comment]
+1

**Comment by toshiossada** [comment]
This is not possible, you just can do  {"key":"value_string"}
